name: Auto Restart and Keep Codespace Active

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute
  workflow_dispatch:

jobs:
  restart_codespace:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI with GitHub Token
        run: |
          echo "${{ secrets.MY_GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check Codespace Status and Keep Alive
        env:
          CODESPACE_NAME: ${{ secrets.MY_CODESPACE_NAME }}
        run: |
          STATUS=$(gh codespace list --json name,state | jq -r --arg name "$CODESPACE_NAME" '.[] | select(.name == $name) | .state')

          if [ -z "$STATUS" ]; then
            echo "Error fetching codespace status or codespace does not exist."
            exit 1
          fi

          echo "Codespace status: $STATUS"

          if [ "$STATUS" == "Shutdown" ]; then
            echo "Codespace is offline. Attempting to start it..."
            gh codespace ssh --codespace $CODESPACE_NAME -- echo 'Codespace started!'
          else
            echo "Codespace is active. Sending keep-alive signal..."
            gh codespace ssh --codespace $CODESPACE_NAME -- echo 'Keep-alive signal'
          fi
